import { createTheme } from "@modulz/design-system";
import {
  gray,
  mauve,
  slate,
  sage,
  olive,
  sand,
  tomato,
  red,
  crimson,
  pink,
  plum,
  purple,
  violet,
  indigo,
  blue,
  sky,
  mint,
  cyan,
  teal,
  green,
  grass,
  lime,
  yellow,
  amber,
  orange,
  brown,
  bronze,
  gold,
  grayDark,
  mauveDark,
  slateDark,
  sageDark,
  oliveDark,
  sandDark,
  tomatoDark,
  redDark,
  crimsonDark,
  pinkDark,
  plumDark,
  purpleDark,
  violetDark,
  indigoDark,
  blueDark,
  skyDark,
  mintDark,
  cyanDark,
  tealDark,
  greenDark,
  grassDark,
  limeDark,
  yellowDark,
  amberDark,
  orangeDark,
  brownDark,
  bronzeDark,
  goldDark,
  whiteA,
  blackA,
} from "@radix-ui/colors";

const fonts = {
  body: "Inter, -apple-system, system-ui, sans-serif",
  mono: "menlo, monospace",
};

const lightThemeColors = {
  ...gray,
  ...mauve,
  ...slate,
  ...sage,
  ...olive,
  ...sand,
  ...tomato,
  ...red,
  ...crimson,
  ...pink,
  ...plum,
  ...purple,
  ...violet,
  ...indigo,
  ...blue,
  ...sky,
  ...mint,
  ...cyan,
  ...teal,
  ...green,
  ...grass,
  ...lime,
  ...yellow,
  ...amber,
  ...orange,
  ...brown,
  ...bronze,
  ...gold,
  ...whiteA,
  ...blackA,
};

const darkThemeColors = {
  ...grayDark,
  ...mauveDark,
  ...slateDark,
  ...sageDark,
  ...oliveDark,
  ...sandDark,
  ...tomatoDark,
  ...redDark,
  ...crimsonDark,
  ...pinkDark,
  ...plumDark,
  ...purpleDark,
  ...violetDark,
  ...indigoDark,
  ...blueDark,
  ...skyDark,
  ...mintDark,
  ...cyanDark,
  ...tealDark,
  ...greenDark,
  ...grassDark,
  ...limeDark,
  ...yellowDark,
  ...amberDark,
  ...orangeDark,
  ...brownDark,
  ...bronzeDark,
  ...goldDark,
  ...whiteA,
  ...blackA,
};

export const naturalPairings = {
  tomato: "mauve",
  red: "mauve",
  crimson: "mauve",
  pink: "mauve",
  plum: "mauve",
  purple: "mauve",
  violet: "mauve",

  indigo: "slate",
  blue: "slate",
  sky: "slate",
  cyan: "slate",

  teal: "sage",
  mint: "sage",
  green: "sage",

  grass: "olive",
  lime: "olive",

  yellow: "sand",
  amber: "sand",
  orange: "sand",
  brown: "sand",
};

function getThemes() {
  const themes: any = {};
  for (const [primary, neutral] of Object.entries(naturalPairings)) {
    themes[`light-theme-${primary}`] = createTheme(`light-theme-${primary}`, {
      colors: {
        ...lightThemeColors,

        // Semantic colors
        primary1: `$${primary}1`,
        primary2: `$${primary}2`,
        primary3: `$${primary}3`,
        primary4: `$${primary}4`,
        primary5: `$${primary}5`,
        primary6: `$${primary}6`,
        primary7: `$${primary}7`,
        primary8: `$${primary}8`,
        primary9: `$${primary}9`,
        primary10: `$${primary}10`,
        primary11: `$${primary}11`,
        primary12: `$${primary}12`,

        neutral1: `$${neutral}1`,
        neutral2: `$${neutral}2`,
        neutral3: `$${neutral}3`,
        neutral4: `$${neutral}4`,
        neutral5: `$${neutral}5`,
        neutral6: `$${neutral}6`,
        neutral7: `$${neutral}7`,
        neutral8: `$${neutral}8`,
        neutral9: `$${neutral}9`,
        neutral10: `$${neutral}10`,
        neutral11: `$${neutral}11`,
        neutral12: `$${neutral}12`,

        hiContrast: `$${neutral}12`,
        loContrast: "$whiteA12",
        canvas: "hsl(0 0% 93%)",
        panel: `$${neutral}2`,
        transparentPanel: "hsl(0 0% 0% / 97%)",
        shadowLight: "hsl(206 22% 7% / 35%)",
        shadowDark: "hsl(206 22% 7% / 20%)",
      },
      fonts,
    });

    themes[`dark-theme-${primary}`] = createTheme(`dark-theme-${primary}`, {
      colors: {
        ...darkThemeColors,

        // Semantic colors
        primary1: `$${primary}1`,
        primary2: `$${primary}2`,
        primary3: `$${primary}3`,
        primary4: `$${primary}4`,
        primary5: `$${primary}5`,
        primary6: `$${primary}6`,
        primary7: `$${primary}7`,
        primary8: `$${primary}8`,
        primary9: `$${primary}9`,
        primary10: `$${primary}10`,
        primary11: `$${primary}11`,
        primary12: `$${primary}12`,

        neutral1: `$${neutral}1`,
        neutral2: `$${neutral}2`,
        neutral3: `$${neutral}3`,
        neutral4: `$${neutral}4`,
        neutral5: `$${neutral}5`,
        neutral6: `$${neutral}6`,
        neutral7: `$${neutral}7`,
        neutral8: `$${neutral}8`,
        neutral9: `$${neutral}9`,
        neutral10: `$${neutral}10`,
        neutral11: `$${neutral}11`,
        neutral12: `$${neutral}12`,

        hiContrast: `$${neutral}12`,
        loContrast: `$${neutral}1`,
        canvas: "hsl(0 0% 15%)",
        panel: `$${neutral}2`,
        transparentPanel: "hsl(0 100% 100% / 97%)",
        shadowLight: "hsl(206 22% 7% / 35%)",
        shadowDark: "hsl(206 22% 7% / 20%)",
      },
      fonts,
    });
  }
  return themes;
}

export const themes = getThemes();

export {
  styled,
  css,
  getCssText,
  globalCss,
  keyframes,
} from "@modulz/design-system";
