name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  lint:
    name: "Build"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3.0.0
      - name: Install
        run: pnpm i
      - name: Build Bundle
        run: pnpm build
